import { Highlight } from "@tiptap/extension-highlight";
import { MarkdownMark } from 'tiptap-markdown';
import markdownitMark from 'markdown-it-mark';

export const MarkdownHighlight = MarkdownMark.create(Highlight, {
    serialize: {
        open: '==',
        close: '==',
    },
    parse: {
        setup(markdownit) {
            markdownit.use(markdownitMark);
        },
        updateDOM() {
            // here you can update HTML generated by markdown-it
        }
    }
});
